SulinOS added.
flatpak/flatpak.github.io pull request #374
Opened 2020-04-19 12:54 UTC by sulincix

SulinOS install guide added.

2020-04-19 13:00 UTC, sulincix commented
hmmm
we need fix

2020-04-19 13:11 UTC, sulincix commented
![photo_2020-04-19_12-31-41](https://user-images.githubusercontent.com/55052890/79688676-4e834e00-823f-11ea-90a8-e01840099f38.jpg)
flatpak works well

2020-04-19 16:22 UTC, frknkrc44 commented
Looks good 😋 please merge it

Because SulinOS is an independent base GNU/Linux distro and current installation ways don't compatible with this distro

2020-04-19 21:32 UTC, paledega commented
Nice
SulinOS is good distro.

2020-04-20 11:14 UTC, AsciiWolf commented
Is the graphical installation of Flatpaks supported? If not, you should add `<p>Note: graphical installation of Flatpak apps may not be possible with SulinOS.</p>` (just like, for example, Gentoo).

2020-04-20 11:16 UTC, AsciiWolf commented
By the way, just wondering: How big is the SulinOS user base? To be honest, this is the first time I heard about this distro.

2020-04-20 21:56 UTC, mwleeds commented
The CI is failing in strange ways on this.

2020-04-21 09:16 UTC, paledega commented
> Is the graphical installation of Flatpaks supported? If not, you should add `<p>Note: graphical installation of Flatpak apps may not be possible with SulinOS.</p>` (just like, for example, Gentoo).

Sulin does not have any graphical installer. (may we will create in next times)

2020-04-21 09:19 UTC, paledega commented
> By the way, just wondering: How big is the SulinOS user base? To be honest, this is the first time I heard about this distro.

SulinOS indipendent distro. Uses inary package manager and Openrc. 
Https://sulinos.github.io

2020-04-21 09:20 UTC, paledega commented
> The CI is failing in strange ways on this.

what we can do

2020-04-21 12:08 UTC, AsciiWolf requested changes

2020-04-21 12:08 UTC, AsciiWolf commented on data/distro.yml
> +        <p>To complete setup, restart your system. Now all you have to do is <a href="https://flathub.org/">install some apps</a>!</p>
Needs information about graphical installation not being possible, see: https://github.com/flatpak/flatpak.github.io/pull/374#issuecomment-616483391

2020-04-21 12:12 UTC, AsciiWolf commented
> SulinOS indipendent distro. Uses inary package manager and Openrc.
> [Https://sulinos.github.io](Https://sulinos.github.io)

And how big (approximately) is its user base? :-)

2020-04-22 23:26 UTC, sulincix commented
SulinOS is turkey origin distro. Most of turkish users may use sulinos. (I never track usage)
Bu our telegram community group has 500+ member (Turkish group)
Hovewer SulinOS is global distro. Non-turkish users using sulinos. 


Graphical install not possible yet. I will add this sentence in pull request.
Thanks for attention

2020-04-23 12:10 UTC, AsciiWolf approved these changes

2020-04-23 23:22 UTC, paledega commented
now We need to fix CI error.

2020-04-24 07:03 UTC, barthalion commented
` Loading data file "/github/workspace/data/distro.yml" failed due to an error: (/github/workspace/data/distro.yml): did not find expected '-' indicator while parsing a block collection at line 1 column 1`

Your changes are probably indented wrongly. Compare it with other entires in distro.yml file.

2020-04-25 02:42 UTC, sulincix commented
I found bug.
I fixed it.

2020-04-27 07:43 UTC, merged